const {app,  BrowserWindow,  ipcMain, dialog} = require('electron');
const fs = require('fs')
const path  = require('path')

function createWindow(){
    const win = new BrowserWindow({
        width: 1400,
        height: 800,
        minWidth:  1100,
        minHeight: 700,
        frame: true,
        backgroundColor: '#f7f9fb',
        webPreferences: {
            preload: path.join(__dirname, 'preload.js'),
            contextIsolation: true,
            nodeIntegration: false,
        }
    });

    win.loadFile(path.join(__dirname, 'index.html'));
}


app.whenReady().then(() => {
    createWindow
})

//to  save barcode as a png
ipcMain.handle('export-png',  async(event, data) => {
    const  {filePath,  canceled} = await dialog.showSaveDialog({
        title: 'Export as PNG',
        defaultPath: 'barcode.png',
        filters: [{name: 'PNG Image', extensions: ['png']}]
    })
    if(canceled || !filePath) return  {success:  false}

    console.log('imageData prefix:', data.imageData.substring(0, 50))
    console.log('filePath:', filePath)


    const base64 = data.imageData.split(',')[1]

    console.log('base64 start:', base64.substring(0, 30))

    fs.writeFileSync(filePath, base64, 'base64')

    return {success: true,  filePath}
})

//SVG export
ipcMain.handle('export-svg', async(event, data)=>{
    const {filePath, canceled} = await dialog.showSaveDialog({
        title: 'Export as SVG',
        default: 'barcode.svg',
        filters: [{name: 'SVG File', extensions: ['svg']}]
    })
    if(canceled || !filePath) return {success: false}

    fs.writeFileSync(filePath,  data.svgData, 'utf8')

    return {success:  true,  filePath}
})

//pdf export
ipcMain.handle('export-pdf', async(event,   data) => {
    const {filePath, canceled}  = await dialog.showSaveDialog({
        title: 'Export as PDF',
        default: 'barcode.pdf',
        filters: [{name: 'PDF File', extensions: ['pdf']}]
    })

    if(canceled ||  !filePath) return {success: false}

    const printWin = new BrowserWindow({
        width: 800,
        height: 600,
        show: false,
        webPreferences: {
            contextIsolation: true,
            nodeIntegration:  false
        }
    })

    const html = `
    <!DOCTYPE html>
    <html>
        <head>
            <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
            background: #ffffff;
            font-family: 'Space Grotesk', sans-serif;
          }
          img {
            max-width: 90%;
            height: auto;
          }
          .label {
            margin-top: 16px;
            font-size: 11px;
            color: #717c82;
            letter-spacing: 0.1em;
            text-transform: uppercase;
          }
        </style>
      </head>
      <body>
        <img src="${data.imageData}" />
        <div class="label">Generated by Barcode Atelier</div>
      </body>
    </html>
    `
    await printWin.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(html)}`)

    //const  win =  BrowserWindow.getFocusedWindow()
    const pdfData = await  printWin.webContents.printToPDF({
        printBackground: true,
        pageSize:  'A4',
        margins: {
      top   : 0.5,   // inches
      bottom: 0.5,
      left  : 0.5,
      right : 0.5
    }
    })

    printWin.close()

    fs.writeFileSync(filePath, pdfData)

    return {success: true, filePath}
})


app.on('window-all-closed',   () =>{
    if(process.platform !==  'darwin'){
        app.quit()
    }
})

app.on('activate', () =>{
    if(BrowserWindow.getAllWindows().length == 0){
        createWindow()
    }
})